name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  tests_accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drashland/website/actions/environment-setup@main
      - uses: denolib/setup-deno@v2

      - name: Start local server
        run: |
          yarn server &
          sleep 10

      - name: Run accessibility tests
        run: |
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445/drash

  tests_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drashland/website/actions/environment-setup@main
      - uses: denolib/setup-deno@v2

      - name: Start local server
        run: |
          yarn server &
          sleep 10

      - name: Run integration tests
        run: |
          deno test -A tests/integration

  tests_pre_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drashland/website/actions/environment-setup@main
      - uses: denolib/setup-deno@v2

      - name: Test pre-release workflow
        run: |
          node console/update_module_versions.js \
            --module drash \
            --version release-v1.0.0

  tests_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: drashland/website/actions/environment-setup@main
      - uses: denolib/setup-deno@v2

      - name: Build Docker image
        run: |
          yarn docker:build-production

      - name: Test Docker application
        run: |
          docker run --detach --rm --name website --publish 1446:1445 drashland-website
          deno test -A tests/docker

  # Lint roll
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2

      - name: Check formatting
        run: |
          deno fmt app.ts server.ts src/resources tests --check

      - name: Lint the codebase
        run: |
          deno lint --unstable src/resources tests
